apiVersion: apps/v1
kind: Deployment
metadata:
  name: color-game-deployment
  labels:
    app: color-game
spec:
  replicas: 1
  selector:
    matchLabels:
      app: color-game
  template:
    metadata:
      labels:
        app: color-game
    spec:
      containers:
        - name: color-game
          image: manoharshetty507/color-game:v1
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: color-service
spec:
  type: NodePort
  selector:
    app: color-game
  ports:
      port: 6001
      targetPort: 80
